baseURL = "https://furso.blog"
title = "Uladzimir Furso"
theme = "hugo-theme-m10c"
DisqusShortname = "furso-blog"

[params]
  author = "Uladzimir Furso"
  avatar = "avatar.jpg"
  description = "Aspiring Software developer .NET, DDD, Distributed systems, and other scary things."
  DisqusShortname = "furso-blog"
  enableDisqus = true
  highlight = true
  highlightStyle = "monokai"
  highlightLanguages = ["javascript", "csharp", "json", "sql", "fsharp", "typescript"]
  katexVersion = "0.11.1"

  [[params.social]]
    name = "github"
    url = "https://github.com/uladzimir-furso"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/uladzimir_furso"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
